### ISSUE TITLE
Instructions for "npm run build"

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist-skills/skill#95]
Are there some setup instructions for gql:gen?  My attempt to run this locally result in:

```
> @atomist/skill@0.3.2 gql:gen /Users/slim/atomist/skill
> graphql-codegen

internal/modules/cjs/loader.js:625
  throw e;
  ^

Error: No valid exports main found for '/Users/slim/atomist/skill/node_modules/extract-files'
    at resolveExportsTarget (internal/modules/cjs/loader.js:622:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/slim/atomist/skill/node_modules/graphql-request/dist/createRequestBody.js:6:23)
    at Module._compile (internal/modules/cjs/loader.js:1139:30) {
  code: 'MODULE_NOT_FOUND'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @atomist/skill@0.3.2 gql:gen: `graphql-codegen`
npm ERR! Exit status 1
```

**Comment by cdupuis** [comment]
No, just running `nom install` and then `nom run build` should do it. No special setup needed.

**Comment by slimslenderslacks** [comment]
For some reason, this doesn't work for me.  Should I look at the version of node or npm that I'm running?

**Comment by ddgenome** [comment]
Can you provide a transcript from your terminal when you run the following commands in the project directory:

```console
$ node --version
$ npm --version
$ git status
$ npm ci
$ npm run build
```

**Comment by slimslenderslacks** [comment]
Thanks!

```
✔ ~/atomist/skill [main|✔]
11:41 $ node --version
v13.5.0
✔ ~/atomist/skill [main|✔]
11:41 $ npm --version
6.13.4
✔ ~/atomist/skill [main|✔]
11:42 $ git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
✔ ~/atomist/skill [main|✔]
11:42 $ npm ci
npm WARN prepare removing existing node_modules/ before installation

> core-js@2.6.11 postinstall /Users/slim/atomist/skill/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> bufferutil@4.0.1 install /Users/slim/atomist/skill/node_modules/bufferutil
> node-gyp-build


> utf-8-validate@5.0.2 install /Users/slim/atomist/skill/node_modules/utf-8-validate
> node-gyp-build


> protobufjs@6.9.0 postinstall /Users/slim/atomist/skill/node_modules/protobufjs
> node scripts/postinstall


> husky@4.3.0 install /Users/slim/atomist/skill/node_modules/husky
> node husky install

husky > Setting up git hooks
husky > Done

> husky@4.3.0 postinstall /Users/slim/atomist/skill/node_modules/husky
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate

added 1094 packages in 16.028s
✔ ~/atomist/skill [main|✔]
11:42 $ npm run build

> @atomist/skill@0.3.2 build /Users/slim/atomist/skill
> run-s clean compile test lint doc


> @atomist/skill@0.3.2 clean /Users/slim/atomist/skill
> run-p clean:compile clean:test clean:doc clean:run


> @atomist/skill@0.3.2 clean:compile /Users/slim/atomist/skill
> rimraf git-info.json build "index.{d.ts,js}{,.map}" "{bin,lib,test}/**/*.{d.ts,js}{,.map}" lib/typings/types.ts


> @atomist/skill@0.3.2 clean:doc /Users/slim/atomist/skill
> rimraf doc


> @atomist/skill@0.3.2 clean:test /Users/slim/atomist/skill
> rimraf .nyc_output coverage


> @atomist/skill@0.3.2 clean:run /Users/slim/atomist/skill
> rimraf *-v8.log profile.txt log


> @atomist/skill@0.3.2 compile /Users/slim/atomist/skill
> run-s gql:gen compile:ts


> @atomist/skill@0.3.2 gql:gen /Users/slim/atomist/skill
> graphql-codegen

internal/modules/cjs/loader.js:625
  throw e;
  ^

Error: No valid exports main found for '/Users/slim/atomist/skill/node_modules/extract-files'
    at resolveExportsTarget (internal/modules/cjs/loader.js:622:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/slim/atomist/skill/node_modules/graphql-request/dist/createRequestBody.js:6:23)
    at Module._compile (internal/modules/cjs/loader.js:1139:30) {
  code: 'MODULE_NOT_FOUND'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @atomist/skill@0.3.2 gql:gen: `graphql-codegen`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @atomist/skill@0.3.2 gql:gen script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/slim/.npm/_logs/2020-10-20T18_42_36_054Z-debug.log
ERROR: "gql:gen" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @atomist/skill@0.3.2 compile: `run-s gql:gen compile:ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @atomist/skill@0.3.2 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/slim/.npm/_logs/2020-10-20T18_42_36_086Z-debug.log
ERROR: "compile" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @atomist/skill@0.3.2 build: `run-s clean compile test lint doc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @atomist/skill@0.3.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/slim/.npm/_logs/2020-10-20T18_42_36_111Z-debug.log
✘-1 ~/atomist/skill [main|✔]
```

**Comment by ddgenome** [comment]
Looks like Node 13.5.0 is broken, https://github.com/strongloop/loopback-next/issues/5381#issuecomment-626288815 . Try upgrading Node and trying again.

**Comment by slimslenderslacks** [comment]
Have just upgraded to 14.14.0 - working now!

**Comment by vakkisan** [comment]
> Looks like Node 13.5.0 is broken, [strongloop/loopback-next#5381 (comment)](https://github.com/strongloop/loopback-next/issues/5381#issuecomment-626288815) . Try upgrading Node and trying again.
> 
> I am able to run those commands successfully with node v14.8.0 and npm 6.14.7.

It fixed after node upgrade
